apiVersion: apps/v1
kind: Deployment
metadata:
  name: medibook-app
  namespace: medibook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medibook-app
  template:
    metadata:
      labels:
        app: medibook-app
    spec:
      containers:
      - name: medibook-app
        image: medibook:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
