apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
metadata:
  name: medibook-cluster
spec:
  nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 30000
      hostPort: 3000
      protocol: TCP
  - role: worker
  - role: worker
