apiVersion: v1
kind: Service
metadata:
  name: medibook-service
  namespace: medibook
spec:
  selector:
    app: medibook-app
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30000
  type: NodePort
