kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: app-hpa
  namespace: app-ns

spec:
  scaleTargetRef:
    kind: Deployment
    name: app-deployment
    apiVersion: apps/v1

  minReplicas: 3
  maxReplicas: 6

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 5
